# Définir cette configuration Compose afin de lancer l'application
# The Computer Club's Blog en production.
version: '3'
services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 20s
    volumes:
      - db_data:/var/lib/postgresql/data
  rocket:
    ports:
      - "$PORT:$PORT"
    environment:
      - DATABASE_URL=$DATABASE_URL
      - ROCKET_ADDRESS=$ROCKET_ADDRESS
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
        restart: true


volumes:
  db_data:
    driver: local
